baseURL                           = "https://conforense.github.io/"   # Your domain name. Must end with "/"
theme                             = "introduction"
DefaultContentLanguage            = "es"                    # Default language for multilingual sites
googleAnalytics                   = "G-337655WCG8"                     # https://gohugo.io/templates/internal/#google-analytics

[params]
    themeStyle                    = "dark"                  # Choose "light" or "dark" or "auto"
    fadeIn                        = true                    # Turn on/off the fade-in effect
    fadeInIndex                   = true                    # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                    = "2 January 2006"
    #email                        = "youremail@email.com"    # E-mail address for contact section
    
    # Configure the home page
    [params.home]
        introHeight               = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest                = true                    # Show latest blog post summary
        showAllPosts              = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        allPostsArchiveFormat     = true                    # show all posts in an archive format
        numberOfConferencesToShow = 3                       # Maximum number of conferences to show on home page. Unset or comment out to show all projects
        localTime                 = false                   # Show your current local time in contact section
        timeZone                  = "Europe/Madrid"         # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat                = "es-ES"                 # Language specific format to use
    [params.conferences]
        useTwoColumns             = false                   # Use a layout with two columns instead of three
        useOneColumn              = true

    # Share buttons on blog post pages
    [params.share]
        twitter                   = true
        facebook                  = false
        pinterest                 = false

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://twitter.com/ConForense"
        icon  = "twitter" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url = "https://mailhide.io/e/Me9ejm5r"  # For a direct email link, use "mailto:test@example.org".
        icon = "envelope" # icon name without the 'fa-'
        icon_pack = "fas"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = false